---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-mgmt
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  application:
    name: user-service
server:
  port: 0 